version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch
    environment:      
      - discovery.type=single-node    
    ports:
      - 9200:9200
      - 9300:9300
    
  db:
    image: mariadb
    container_name: db
    environment:
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=password1
      - MYSQL_DATABASE=mydb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306

  web:
    build: .
    working_dir: /
    depends_on:
        - elasticsearch
    volumes:
      - './app:/app'   
    ports:
      - '8990:8989'

  